name: Update App Screenshots

on:
  push:
    branches: [ main ]
    paths:
      - 'app/src/main/res/layout/**'
      - 'app/src/main/res/drawable/**'
      - 'app/src/main/res/values/styles.xml'
      - 'app/src/main/res/values/themes.xml'
      - 'app/src/main/res/values/colors.xml'
      - 'app/src/main/kotlin/com/scrolless/app/features/**/*.kt'
      - 'libraries/components/src/main/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'app/src/main/res/layout/**'
      - 'app/src/main/res/drawable/**'
      - 'app/src/main/res/values/styles.xml'
      - 'app/src/main/res/values/themes.xml'
      - 'app/src/main/res/values/colors.xml'
      - 'app/src/main/kotlin/com/scrolless/app/features/**/*.kt'
      - 'libraries/components/src/main/**'
  workflow_dispatch:  # Allows manual triggering

concurrency:
  group: screenshots-${{ github.ref }}
  cancel-in-progress: true

jobs:
  screenshots:
    name: Generate App Screenshots
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      
      - name: Run all screenshot tests (Roborazzi)
        id: screenshotsverify
        continue-on-error: true
        run: ./gradlew verifyRoborazziDebug
      
      - name: Prevent pushing new screenshots if this is a fork
        id: checkfork_screenshots
        continue-on-error: false
        if: steps.screenshotsverify.outcome == 'failure' && github.event.pull_request.head.repo.full_name != github.repository
        run: |
          echo "::error::Screenshot tests failed, please create a PR in your fork first." 
          echo "Your fork's CI will take screenshots for your fork."
          exit 1
      
      # Runs if previous job failed
      - name: Generate new screenshots if verification failed and it's a PR
        id: screenshotsrecord
        if: steps.screenshotsverify.outcome == 'failure' && github.event_name == 'pull_request'
        run: |
          ./gradlew recordRoborazziDebug
      
      - name: Upload screenshot results (PNG)
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-test-results
          path: '**/build/outputs/roborazzi/*.png'
      
      - name: Copy screenshots to art folder
        run: |
          mkdir -p art/screenshots
          cp -R **/build/outputs/roborazzi/*.png art/screenshots/ || echo "No screenshots found"
          
      - name: Update main screenshots
        run: |
          cp art/screenshots/home_screen.png art/scrollessapp.png || echo "Main screenshot not found"
          # Add more specific screenshot copies if needed
      
      - name: Push new screenshots if available
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'art/**/*.png'
          disable_globbing: false
          commit_message: "🤖 Updates app screenshots [skip ci]"